
-- This file is auto generated by uaflex. Don't edit
package body Ada_Lexer is

   ---------------
   -- Get_Class --
   ---------------

   function Get_Class (C : Wide_String) return Character_Class is
      Pos : constant Natural := Wide_Character'Pos (C (C'First));
   begin
      case Pos is
         when  9
           |  11
           |  12
           |  13 =>
            return 0;
         when  10 =>
            return 1;
         when  14 .. 31 =>
            return 2;
         when  34 =>
            return 3;
         when  32 =>
            return 4;
         when  33 =>
            return 5;
         when  37 =>
            return 6;
         when  36
           |  63 .. 64
           |  91 .. 94
           |  96
           |  123
           |  125 .. 1114111 =>
            return 7;
         when  60 =>
            return 8;
         when  62 =>
            return 9;
         when  42 =>
            return 10;
         when  46 =>
            return 11;
         when  47 =>
            return 12;
         when  58 =>
            return 13;
         when  61 =>
            return 14;
         when  39 =>
            return 15;
         when  38 =>
            return 16;
         when  40 =>
            return 17;
         when  41 =>
            return 18;
         when  44 =>
            return 19;
         when  59 =>
            return 20;
         when  124 =>
            return 21;
         when  95 =>
            return 22;
         when  35 =>
            return 23;
         when  45 =>
            return 24;
         when  43 =>
            return 25;
         when  73
           |  105 =>
            return 26;
         when  84
           |  116 =>
            return 27;
         when  79
           |  111 =>
            return 28;
         when  78
           |  110 =>
            return 29;
         when  83
           |  115 =>
            return 30;
         when  69
           |  101 =>
            return 31;
         when  65
           |  97 =>
            return 32;
         when  76
           |  108 =>
            return 33;
         when  85
           |  117 =>
            return 34;
         when  67
           |  99 =>
            return 35;
         when  82
           |  114 =>
            return 36;
         when  80
           |  112 =>
            return 37;
         when  70
           |  102 =>
            return 38;
         when  71
           |  103 =>
            return 39;
         when  77
           |  109 =>
            return 40;
         when  72
           |  104 =>
            return 41;
         when  86
           |  118 =>
            return 42;
         when  68
           |  100 =>
            return 43;
         when  87
           |  119 =>
            return 44;
         when  66
           |  98 =>
            return 45;
         when  88
           |  120 =>
            return 46;
         when  89
           |  121 =>
            return 47;
         when  81
           |  113 =>
            return 48;
         when  75
           |  107 =>
            return 49;
         when  74
           |  90
           |  106
           |  122 =>
            return 50;
         when  48 .. 57 =>
            return 51;
         when others =>
            return 53;
      end case;
   end Get_Class;

end Ada_Lexer;
